### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by xsstomy** [papandreou/node-pngquant#104]
![image](https://github.com/papandreou/node-pngquant/assets/8943787/f4cc947f-4e45-4a38-ba30-fe178013c658)

![image](https://github.com/papandreou/node-pngquant/assets/8943787/1276aa30-6031-46cd-ada1-ab85cfa8aacd)

node 16 

how can i fix this ?

windows os

thank you

**Comment by papandreou** [comment]
I have no idea what you're trying to do. Please provide actual reproduction steps.

**Comment by xsstomy** [comment]
i found that the pngquant binary is  not in my PATH.


![image](https://github.com/papandreou/node-pngquant/assets/8943787/a2d7db93-0fcd-4715-b3be-ff7dbb7c86b1)

when i use this function ,error above

**Comment by papandreou** [comment]
@ubermanu seems to understand what the problem is. I've published 4.2.0 with the fix, could you try with that?

**Comment by xsstomy** [comment]
![image](https://github.com/papandreou/node-pngquant/assets/8943787/8cbd5375-710e-4c27-9474-47e4aeab4df9)

![image](https://github.com/papandreou/node-pngquant/assets/8943787/98ab38f3-1d17-401e-8e15-9174e6ab4a64)

new error 

@papandreou

**Comment by ubermanu** [comment]
Somehow i had the same issue, but managed to make it work using a compact quality arg:

```js
new PngQuant([192, "--quality=60-80", "--nofs", "-"])
```
