### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by kamcknig** [papandreou/node-pngquant#5]
When trying to install this on Windows I get the following error:

> pngquant-bin@2.0.0 postinstall D:\development\angular-development\AngularJS\AngularJS Patterns\sample_code\modular\node_modules\pngquant\node_modules\pngquant-bin
> node lib/install.js

\
     warn : pngquant pre-build test failed
     info : compiling from source
    error : Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:647:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Socket.<anonymous> (child_process.js:968:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)

pngquant@0.4.0 node_modules\pngquant
└── pngquant-bin@2.0.0 (imagemin-log@1.0.2, bin-wrapper@2.1.3, bin-build@2.1.1)

**Comment by papandreou** [comment]
Does it work? `pngquant-bin` (which tries and fails to compile pngquant) is listed under `optionalDependencies`, so if you have a `pngquant` binary in your $PATH, it should still be picked up by this module.

**Comment by kamcknig** [comment]
OK i do have pngquant in my path so I will test it to see if it works. Thanks!

**Comment by anthonyaam** [comment]
This issue should be closed.

**Comment by papandreou** [comment]
Fair, let’s assume it got resolved :smirk:
