### ISSUE TITLE
Different pngquant-bin versions

### ISSUE THREAD

**Issue by koutsenko** [papandreou/node-pngquant#8]
On linux and windows machine there will be different pngquant bin installed.
They support different command line keys.
Also, 2.2.0 version png compression is much better than 2.4.0!

pngquant npm package version: 0.6.0
windows pngquant binary: 2.4.0 based on libpng 1.6.17
ubuntu pngquant binary: 2.2.0 based on libpng 1.2.46 (compiled) and 1.2.50 (used)

**Comment by koutsenko** [comment]
The temporary solution is to fix pngquant version in package.json, e.g. I use pngquant@0.4.0, it installs almost compatible pngquant-bin versions, 2.2.0 on linx and 2.1.1 on windows

**Comment by simeyla** [comment]
What about now?

Latest version is 2.12 which appears to have [many improvements](https://raw.githubusercontent.com/kornelski/pngquant/master/CHANGELOG)

**Comment by papandreou** [comment]
Sorry for not noticing this issue!

The binary is provided by [the `pngquant-bin` package](https://www.npmjs.com/package/pngquant-bin), so the issue should be raised there.

Based on the latest commit messages in [this directory](https://github.com/imagemin/pngquant-bin/tree/master/vendor), it looks like it's still providing different versions depending on the OS.
